version: "3.3"
services:
  asir_bind9:
    container_name: asir_bind9
    image: internetsystemsconsortium/bind9:9.16
    ports:
      - 5300:53/tcp
      - 5300:53/udp
    networks:
      alberto:
        ipv4_address: 10.1.0.254
    volumes:
      - /home/asir2a/Escritorio/SRI/practicadns/conf:/etc/bind
      - /home/asir2a/Escritorio/SRI/practicadns/zonas:/var/lib/bind

  alberto_cliente:
    container_name: alberto_cliente
    image: alpine
    networks:
      - alberto
    stdin_open: true  
    tty: true         
    dns:
      - 10.1.0.254  # IP del contenedor dns 
networks:
  bind9_subnet: 
    external: true